# Generated by Django 4.1 on 2023-11-30 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='linkedin_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education_user', to='api.linkedinuser'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='linkedin_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experience_user', to='api.linkedinuser'),
        ),
    ]
